# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        gradle(
          task: "assemble",
          flavor: "dev",
          build_type: "Release",
          properties: {
            "versionCodeArg": ENV['BUILD_NUMBER']
          }
        )
        firebase_app_distribution(
            service_credentials_file: "firebase_credentials.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
    end

    desc "Lane for uploading builds to Google Play Store"
    lane :playstore do
        gradle(
            task: "bundle",
            flavor: "prod",
            build_type: "Release",
            properties: {
                "versionCodeArg" => ENV['BUILD_NUMBER'],
                "storeFile" => ENV['STORE_FILE'],
                "storePassword" => ENV['STORE_PASSWORD'],
                "keyAlias" => ENV['KEY_ALIAS'],
                "keyPassword" => ENV['KEY_PASSWORD']
             }
        )
        upload_to_play_store(
            package_name: "com.rowang.androidtemplate",
            track: "internal",
            release_status: 'draft',
            json_key: "play_store_credentials.json",
            aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
        )
    end
end
